name: Deploy Both

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-front:
    runs-on: ubuntu-latest

    steps:
      ###################################################
      # 1) Pull le FRONT depuis un autre repo
      ###################################################
      - name: Get new-eateaze-front
        run: |
          cd /var/www/tousalaferme/new-eateaze-front
          git pull origin main
          npm ci

      ###################################################
      # 2) Build le FRONT
      ###################################################
      - name: Build front
        run: |
          cd /var/www/tousalaferme/new-eateaze-front
          npm run build

      ###################################################
      # 3) SCP du build sur le VPS
      ###################################################
      - name: Deploy front to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}         # IP du VPS ex: 217.xxx...
          username: ubuntu                      # ou root, selon la clé
          key: ${{ secrets.SSH_KEY }}           # Clé privée SSH
          source: "front/build/*"
          target: "/var/www/tousalaferme/new-eateaze-front/build"
          port: 22                              # ou un autre si SSH n'est pas sur 22

      ###################################################
      # 4) Reload Nginx
      ###################################################
      - name: Reload Nginx
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            sudo systemctl reload nginx
