name: Deploy Front

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Pas de checkout local. On n'en a pas besoin, 
      #    car tout se fait sur le VPS.
      #    (Tu peux mettre un "uses: actions/checkout@v3" 
      #     si tu veux, mais il n'est pas utile pour un build sur le VPS.)

      - name: SSH into VPS and build
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          # si c'est un autre port SSH, specify: port: 2222
          script: |
            cd /var/www/tousalaferme/new-eateaze-front
            git pull
            npm install
            npm run build
            sudo systemctl reload nginx
