name: Deploy Front

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Copy build folder to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}       # IP ou domaine de ton VPS
          username: ubuntu                    # l'utilisateur qui possède la clé publique
          key: ${{ secrets.SSH_KEY }}         # la clé privée (ton secret GitHub)
          port: 22                            # ou un autre port si SSH n'est pas sur 22
          source: "build/*"
          target: "/var/www/tousalaferme/new-eateaze-front/build"

      - name: Reload Nginx
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            sudo systemctl reload nginx
